// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/image_service.proto

package imagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1 // 等待中
	TaskStatus_TASK_STATUS_PROCESSING  TaskStatus = 2 // 处理中
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3 // 已完成
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4 // 失败
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_PROCESSING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_PROCESSING":  2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_image_service_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_image_service_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{0}
}

// HealthStatus 健康状态
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1 // 正常服务
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2 // 不可用
	HealthStatus_HEALTH_STATUS_UNKNOWN     HealthStatus = 3 // 未知状态
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
		"HEALTH_STATUS_UNKNOWN":     3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_image_service_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_proto_image_service_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{1}
}

// GenerateImageRequest 生成图片请求
type GenerateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                               // 提示词
	ImageUrls     []string               `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`                                                        // 参考图片URL（可选）
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                                 // 模型名称（可选）
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`                                                                                   // 图片尺寸（可选）
	Watermark     bool                   `protobuf:"varint,5,opt,name=watermark,proto3" json:"watermark,omitempty"`                                                                        // 是否添加水印
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_proto_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImageRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *GenerateImageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImageRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GenerateImageRequest) GetWatermark() bool {
	if x != nil {
		return x.Watermark
	}
	return false
}

func (x *GenerateImageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GenerateImageResponse 生成图片响应
type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	Images        []*ImageData           `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`                        // 生成的图片
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`                          // 使用统计
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                          // 使用的模型
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_proto_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateImageResponse) GetImages() []*ImageData {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GenerateImageResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GenerateImageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GenerateImageAsyncResponse 异步生成图片响应
type GenerateImageAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`             // 任务ID
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=image.v1.TaskStatus" json:"status,omitempty"` // 任务状态
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageAsyncResponse) Reset() {
	*x = GenerateImageAsyncResponse{}
	mi := &file_proto_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageAsyncResponse) ProtoMessage() {}

func (x *GenerateImageAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageAsyncResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageAsyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateImageAsyncResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GenerateImageAsyncResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GenerateImageAsyncResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GenerateSequentialImagesRequest 生成序列图片请求
type GenerateSequentialImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                               // 提示词
	MaxImages     int32                  `protobuf:"varint,2,opt,name=max_images,json=maxImages,proto3" json:"max_images,omitempty"`                                                       // 最大图片数量
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                                 // 模型名称（可选）
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`                                                                                   // 图片尺寸（可选）
	Watermark     bool                   `protobuf:"varint,5,opt,name=watermark,proto3" json:"watermark,omitempty"`                                                                        // 是否添加水印
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSequentialImagesRequest) Reset() {
	*x = GenerateSequentialImagesRequest{}
	mi := &file_proto_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSequentialImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSequentialImagesRequest) ProtoMessage() {}

func (x *GenerateSequentialImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSequentialImagesRequest.ProtoReflect.Descriptor instead.
func (*GenerateSequentialImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateSequentialImagesRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateSequentialImagesRequest) GetMaxImages() int32 {
	if x != nil {
		return x.MaxImages
	}
	return 0
}

func (x *GenerateSequentialImagesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateSequentialImagesRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GenerateSequentialImagesRequest) GetWatermark() bool {
	if x != nil {
		return x.Watermark
	}
	return false
}

func (x *GenerateSequentialImagesRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetImageTaskRequest 获取图片生成任务请求
type GetImageTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageTaskRequest) Reset() {
	*x = GetImageTaskRequest{}
	mi := &file_proto_image_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageTaskRequest) ProtoMessage() {}

func (x *GetImageTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageTaskRequest.ProtoReflect.Descriptor instead.
func (*GetImageTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetImageTaskResponse 获取图片生成任务响应
type GetImageTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // 任务ID
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=image.v1.TaskStatus" json:"status,omitempty"`       // 任务状态
	Result        *GenerateImageResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                                 // 生成结果（如果完成）
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（如果失败）
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageTaskResponse) Reset() {
	*x = GetImageTaskResponse{}
	mi := &file_proto_image_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageTaskResponse) ProtoMessage() {}

func (x *GetImageTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageTaskResponse.ProtoReflect.Descriptor instead.
func (*GetImageTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetImageTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetImageTaskResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetImageTaskResponse) GetResult() *GenerateImageResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetImageTaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetImageTaskResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetImageTaskResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_image_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{6}
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=image.v1.HealthStatus" json:"status,omitempty"`                                                 // 健康状态
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // 状态信息
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_image_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// ImageData 图片数据
type ImageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                          // 图片URL
	B64Json       string                 `protobuf:"bytes,2,opt,name=b64_json,json=b64Json,proto3" json:"b64_json,omitempty"`                   // Base64编码的图片数据（可选）
	RevisedPrompt string                 `protobuf:"bytes,3,opt,name=revised_prompt,json=revisedPrompt,proto3" json:"revised_prompt,omitempty"` // 修订后的提示词
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	mi := &file_proto_image_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{8}
}

func (x *ImageData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageData) GetB64Json() string {
	if x != nil {
		return x.B64Json
	}
	return ""
}

func (x *ImageData) GetRevisedPrompt() string {
	if x != nil {
		return x.RevisedPrompt
	}
	return ""
}

// Usage 使用统计
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`             // 提示词token数
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"` // 完成token数
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`                // 总token数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_image_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_image_service_proto_rawDescGZIP(), []int{9}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_proto_image_service_proto protoreflect.FileDescriptor

const file_proto_image_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/image_service.proto\x12\bimage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n" +
	"\x14GenerateImageRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x02 \x03(\tR\timageUrls\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x1c\n" +
	"\twatermark\x18\x05 \x01(\bR\twatermark\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.image.v1.GenerateImageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x15GenerateImageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x06images\x18\x02 \x03(\v2\x13.image.v1.ImageDataR\x06images\x12%\n" +
	"\x05usage\x18\x03 \x01(\v2\x0f.image.v1.UsageR\x05usage\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9e\x01\n" +
	"\x1aGenerateImageAsyncResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.image.v1.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb2\x02\n" +
	"\x1fGenerateSequentialImagesRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_images\x18\x02 \x01(\x05R\tmaxImages\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x1c\n" +
	"\twatermark\x18\x05 \x01(\bR\twatermark\x12S\n" +
	"\bmetadata\x18\x06 \x03(\v27.image.v1.GenerateSequentialImagesRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x13GetImageTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xb1\x02\n" +
	"\x14GetImageTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.image.v1.TaskStatusR\x06status\x127\n" +
	"\x06result\x18\x03 \x01(\v2\x1f.image.v1.GenerateImageResponseR\x06result\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12HealthCheckRequest\"\xe1\x01\n" +
	"\x13HealthCheckResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.image.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\adetails\x18\x03 \x03(\v2*.image.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\tImageData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\bb64_json\x18\x02 \x01(\tR\ab64Json\x12%\n" +
	"\x0erevised_prompt\x18\x03 \x01(\tR\rrevisedPrompt\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens*\x91\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16TASK_STATUS_PROCESSING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04*\x82\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x032\xbf\x03\n" +
	"\fImageService\x12P\n" +
	"\rGenerateImage\x12\x1e.image.v1.GenerateImageRequest\x1a\x1f.image.v1.GenerateImageResponse\x12Z\n" +
	"\x12GenerateImageAsync\x12\x1e.image.v1.GenerateImageRequest\x1a$.image.v1.GenerateImageAsyncResponse\x12M\n" +
	"\fGetImageTask\x12\x1d.image.v1.GetImageTaskRequest\x1a\x1e.image.v1.GetImageTaskResponse\x12f\n" +
	"\x18GenerateSequentialImages\x12).image.v1.GenerateSequentialImagesRequest\x1a\x1f.image.v1.GenerateImageResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.image.v1.HealthCheckRequest\x1a\x1d.image.v1.HealthCheckResponseB\x1aZ\x18sia/api/image/v1;imagev1b\x06proto3"

var (
	file_proto_image_service_proto_rawDescOnce sync.Once
	file_proto_image_service_proto_rawDescData []byte
)

func file_proto_image_service_proto_rawDescGZIP() []byte {
	file_proto_image_service_proto_rawDescOnce.Do(func() {
		file_proto_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)))
	})
	return file_proto_image_service_proto_rawDescData
}

var file_proto_image_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_image_service_proto_goTypes = []any{
	(TaskStatus)(0),                         // 0: image.v1.TaskStatus
	(HealthStatus)(0),                       // 1: image.v1.HealthStatus
	(*GenerateImageRequest)(nil),            // 2: image.v1.GenerateImageRequest
	(*GenerateImageResponse)(nil),           // 3: image.v1.GenerateImageResponse
	(*GenerateImageAsyncResponse)(nil),      // 4: image.v1.GenerateImageAsyncResponse
	(*GenerateSequentialImagesRequest)(nil), // 5: image.v1.GenerateSequentialImagesRequest
	(*GetImageTaskRequest)(nil),             // 6: image.v1.GetImageTaskRequest
	(*GetImageTaskResponse)(nil),            // 7: image.v1.GetImageTaskResponse
	(*HealthCheckRequest)(nil),              // 8: image.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 9: image.v1.HealthCheckResponse
	(*ImageData)(nil),                       // 10: image.v1.ImageData
	(*Usage)(nil),                           // 11: image.v1.Usage
	nil,                                     // 12: image.v1.GenerateImageRequest.MetadataEntry
	nil,                                     // 13: image.v1.GenerateSequentialImagesRequest.MetadataEntry
	nil,                                     // 14: image.v1.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),           // 15: google.protobuf.Timestamp
}
var file_proto_image_service_proto_depIdxs = []int32{
	12, // 0: image.v1.GenerateImageRequest.metadata:type_name -> image.v1.GenerateImageRequest.MetadataEntry
	10, // 1: image.v1.GenerateImageResponse.images:type_name -> image.v1.ImageData
	11, // 2: image.v1.GenerateImageResponse.usage:type_name -> image.v1.Usage
	15, // 3: image.v1.GenerateImageResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: image.v1.GenerateImageAsyncResponse.status:type_name -> image.v1.TaskStatus
	15, // 5: image.v1.GenerateImageAsyncResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: image.v1.GenerateSequentialImagesRequest.metadata:type_name -> image.v1.GenerateSequentialImagesRequest.MetadataEntry
	0,  // 7: image.v1.GetImageTaskResponse.status:type_name -> image.v1.TaskStatus
	3,  // 8: image.v1.GetImageTaskResponse.result:type_name -> image.v1.GenerateImageResponse
	15, // 9: image.v1.GetImageTaskResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 10: image.v1.GetImageTaskResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: image.v1.HealthCheckResponse.status:type_name -> image.v1.HealthStatus
	14, // 12: image.v1.HealthCheckResponse.details:type_name -> image.v1.HealthCheckResponse.DetailsEntry
	2,  // 13: image.v1.ImageService.GenerateImage:input_type -> image.v1.GenerateImageRequest
	2,  // 14: image.v1.ImageService.GenerateImageAsync:input_type -> image.v1.GenerateImageRequest
	6,  // 15: image.v1.ImageService.GetImageTask:input_type -> image.v1.GetImageTaskRequest
	5,  // 16: image.v1.ImageService.GenerateSequentialImages:input_type -> image.v1.GenerateSequentialImagesRequest
	8,  // 17: image.v1.ImageService.HealthCheck:input_type -> image.v1.HealthCheckRequest
	3,  // 18: image.v1.ImageService.GenerateImage:output_type -> image.v1.GenerateImageResponse
	4,  // 19: image.v1.ImageService.GenerateImageAsync:output_type -> image.v1.GenerateImageAsyncResponse
	7,  // 20: image.v1.ImageService.GetImageTask:output_type -> image.v1.GetImageTaskResponse
	3,  // 21: image.v1.ImageService.GenerateSequentialImages:output_type -> image.v1.GenerateImageResponse
	9,  // 22: image.v1.ImageService.HealthCheck:output_type -> image.v1.HealthCheckResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_image_service_proto_init() }
func file_proto_image_service_proto_init() {
	if File_proto_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_service_proto_rawDesc), len(file_proto_image_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_service_proto_goTypes,
		DependencyIndexes: file_proto_image_service_proto_depIdxs,
		EnumInfos:         file_proto_image_service_proto_enumTypes,
		MessageInfos:      file_proto_image_service_proto_msgTypes,
	}.Build()
	File_proto_image_service_proto = out.File
	file_proto_image_service_proto_goTypes = nil
	file_proto_image_service_proto_depIdxs = nil
}
